### ISSUE TITLE
the missing code for "options"  module

### ISSUE THREAD

**Issue by yummyJade** [VISION-SJTU/3dSwap#1]
Thank you for your great work! 
it seems that there are some missing modules in the code

![image](https://github.com/VISION-SJTU/3dSwap/assets/32930873/e15ea347-1cd8-49c9-8f68-d01bc101288b)

**Comment by lyx0208** [comment]
Sorry, I'll upload it now.

**Comment by lyx0208** [comment]
Done.

**Comment by yummyJade** [comment]
thank u!
