### ISSUE TITLE
the training code can not work properly

### ISSUE THREAD

**Issue by yummyJade** [VISION-SJTU/3dSwap#2]
I use 4x3090 to run the training code, but I encountered an issue where the program became unresponsive during the importing process. 
![image](https://github.com/VISION-SJTU/3dSwap/assets/32930873/8cd4bb52-cfe2-4df9-8378-f090babc7fba)
I use the debugger and find the program stuck in "from models.psp import pSp" => "from models.encoders import psp_encoders"=>"from models.stylegan2.model import EqualLinear" 

the env is : torch 1.9.0+cu111 + torchaudio 0.9.0 + torchvision 0.10.0+cu111 + cuda 11.3

What could be the problem? Thank you!

**Comment by lyx0208** [comment]
Try to delete the "~/.cache/torch_extensions" folder and run the script again.
I think this may help.

**Comment by yummyJade** [comment]
solve it, thank you for your kind help!
